- ros_topic_name: "/scout/force_bar/segment_0"
  gz_topic_name: "/scout/force_bar/segment_0"
  ros_type_name: "geometry_msgs/msg/Wrench"
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS
- ros_topic_name: "/scout/force_bar/segment_1"
  gz_topic_name: "/scout/force_bar/segment_1"
  ros_type_name: "geometry_msgs/msg/Wrench"
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS
- ros_topic_name: "/scout/force_bar/segment_2"
  gz_topic_name: "/scout/force_bar/segment_2"
  ros_type_name: "geometry_msgs/msg/Wrench"
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS
- ros_topic_name: "/scout/force_bar/segment_3"
  gz_topic_name: "/scout/force_bar/segment_3"
  ros_type_name: "geometry_msgs/msg/Wrench"
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS
- ros_topic_name: "/scout/force_bar/segment_4"
  gz_topic_name: "/scout/force_bar/segment_4"
  ros_type_name: "geometry_msgs/msg/Wrench"
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: BIDIRECTIONAL
- ros_topic_name: "/odom"
  gz_topic_name: "/model/scout/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS
- ros_topic_name: "/pose"
  gz_topic_name: "/model/scout/pose"
  ros_type_name: "geometry_msgs/msg/Pose"
  gz_type_name: "gz.msgs.Pose"
  direction: GZ_TO_ROS
- ros_topic_name: "/tf"
  gz_topic_name: "/model/scout/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
- ros_topic_name: "/imu"
  gz_topic_name: "/scout/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS
